# Generated by Django 3.2.8 on 2021-11-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('002', 'London'), ('003', 'New York'), ('001', 'Berlin'), ('06', 'Ankara'), ('07', 'Antalya'), ('004', 'Tokyo'), ('61', 'Trabzon'), ('005', 'Sidney'), ('34', 'Istanbul'), ('35', 'Izmir')], default='06', max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=15)),
                ('date_of_departure', models.DateTimeField()),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.city')),
            ],
            options={
                'ordering': ['-date_of_departure'],
            },
        ),
        migrations.CreateModel(
            name='OperatingAirlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('903', 'Turkish Airlines'), ('902', 'Anadolu Jet'), ('901', 'Onur Air'), ('905', 'Atlasglobal'), ('904', 'Pegasus')], default='06', max_length=50, verbose_name='Airlines')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='operating_airlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.operatingairlines'),
        ),
    ]
