# Generated by Django 3.2.8 on 2021-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('003', 'New York'), ('61', 'Trabzon'), ('004', 'Tokyo'), ('35', 'Izmir'), ('07', 'Antalya'), ('34', 'Istanbul'), ('001', 'Berlin'), ('002', 'London'), ('005', 'Sidney'), ('06', 'Ankara')], default='06', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('901', 'Onur Air'), ('903', 'Turkish Airlines'), ('902', 'Anadolu Jet'), ('905', 'Atlasglobal'), ('904', 'Pegasus')], default='06', max_length=50, verbose_name='Airlines'),
        ),
    ]
