# Generated by Django 3.2.8 on 2021-11-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20211114_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('002', 'London'), ('001', 'Berlin'), ('07', 'Antalya'), ('61', 'Trabzon'), ('34', 'Istanbul'), ('004', 'Tokyo'), ('003', 'New York'), ('06', 'Ankara'), ('005', 'Sidney'), ('35', 'Izmir')], default='06', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='operating_airlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.operatingairlines'),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('901', 'Onur Air'), ('903', 'Turkish Airlines'), ('904', 'Pegasus'), ('905', 'Atlasglobal'), ('902', 'Anadolu Jet')], default='06', max_length=50, verbose_name='Airlines'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.flight'),
        ),
    ]
