# Generated by Django 3.2.8 on 2021-11-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20211114_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('002', 'London'), ('34', 'Istanbul'), ('61', 'Trabzon'), ('003', 'New York'), ('07', 'Antalya'), ('001', 'Berlin'), ('35', 'Izmir'), ('005', 'Sidney'), ('06', 'Ankara'), ('004', 'Tokyo')], default='06', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='flightreservation',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('902', 'Anadolu Jet'), ('901', 'Onur Air'), ('905', 'Atlasglobal'), ('903', 'Turkish Airlines'), ('904', 'Pegasus')], default='06', max_length=50, verbose_name='Airlines'),
        ),
    ]
