# Generated by Django 3.2.8 on 2021-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20211114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('06', 'Ankara'), ('005', 'Sidney'), ('61', 'Trabzon'), ('001', 'Berlin'), ('34', 'Istanbul'), ('003', 'New York'), ('004', 'Tokyo'), ('07', 'Antalya'), ('35', 'Izmir'), ('002', 'London')], default='06', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('903', 'Turkish Airlines'), ('902', 'Anadolu Jet'), ('905', 'Atlasglobal'), ('901', 'Onur Air'), ('904', 'Pegasus')], default='06', max_length=50),
        ),
    ]
