# Generated by Django 3.2.8 on 2021-11-14 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20211114_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('34', 'Istanbul'), ('002', 'London'), ('07', 'Antalya'), ('35', 'Izmir'), ('004', 'Tokyo'), ('005', 'Sidney'), ('001', 'Berlin'), ('06', 'Ankara'), ('61', 'Trabzon'), ('003', 'New York')], default=datetime.datetime(2021, 11, 14, 13, 11, 44, 73578, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('34', 'Istanbul'), ('002', 'London'), ('07', 'Antalya'), ('35', 'Izmir'), ('004', 'Tokyo'), ('005', 'Sidney'), ('001', 'Berlin'), ('06', 'Ankara'), ('61', 'Trabzon'), ('003', 'New York')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('905', 'Atlasglobal'), ('904', 'Pegasus'), ('902', 'Anadolu Jet'), ('901', 'Onur Air'), ('903', 'Turkish Airlines')], default='06', max_length=50),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
