# Generated by Django 3.2.8 on 2021-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20211114_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('35', 'Izmir'), ('003', 'New York'), ('002', 'London'), ('61', 'Trabzon'), ('06', 'Ankara'), ('34', 'Istanbul'), ('07', 'Antalya'), ('004', 'Tokyo'), ('001', 'Berlin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('35', 'Izmir'), ('003', 'New York'), ('002', 'London'), ('61', 'Trabzon'), ('06', 'Ankara'), ('34', 'Istanbul'), ('07', 'Antalya'), ('004', 'Tokyo'), ('001', 'Berlin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('901', 'Onur Air'), ('905', 'Atlasglobal'), ('903', 'Turkish Airlines'), ('904', 'Pegasus'), ('902', 'Anadolu Jet')], default='06', max_length=50),
        ),
    ]
