# Generated by Django 3.2.9 on 2021-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_auto_20211114_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('06', 'Ankara'), ('001', 'Berlin'), ('005', 'Sidney'), ('003', 'New York'), ('07', 'Antalya'), ('002', 'London'), ('004', 'Tokyo'), ('61', 'Trabzon'), ('34', 'Istanbul'), ('35', 'Izmir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('06', 'Ankara'), ('001', 'Berlin'), ('005', 'Sidney'), ('003', 'New York'), ('07', 'Antalya'), ('002', 'London'), ('004', 'Tokyo'), ('61', 'Trabzon'), ('34', 'Istanbul'), ('35', 'Izmir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('903', 'Turkish Airlines'), ('904', 'Pegasus'), ('905', 'Atlasglobal'), ('902', 'Anadolu Jet'), ('901', 'Onur Air')], max_length=50),
        ),
    ]
