# Generated by Django 3.2.9 on 2021-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_auto_20211116_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('61', 'Trabzon'), ('002', 'London'), ('07', 'Antalya'), ('001', 'Berlin'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('003', 'New York'), ('06', 'Ankara'), ('35', 'Izmir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('61', 'Trabzon'), ('002', 'London'), ('07', 'Antalya'), ('001', 'Berlin'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('003', 'New York'), ('06', 'Ankara'), ('35', 'Izmir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('904', 'Pegasus'), ('902', 'Anadolu Jet'), ('901', 'Onur Air'), ('903', 'Turkish Airlines'), ('905', 'Atlasglobal')], max_length=50),
        ),
    ]
