# Generated by Django 3.2.9 on 2021-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20211116_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingairlines',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('35', 'Izmir'), ('003', 'New York'), ('34', 'Istanbul'), ('61', 'Trabzon'), ('001', 'Berlin'), ('004', 'Tokyo'), ('005', 'Sidney'), ('07', 'Antalya'), ('002', 'London'), ('06', 'Ankara')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('35', 'Izmir'), ('003', 'New York'), ('34', 'Istanbul'), ('61', 'Trabzon'), ('001', 'Berlin'), ('004', 'Tokyo'), ('005', 'Sidney'), ('07', 'Antalya'), ('002', 'London'), ('06', 'Ankara')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('902', 'Anadolu Jet'), ('903', 'Turkish Airlines'), ('901', 'Onur Air'), ('905', 'Atlasglobal'), ('904', 'Pegasus')], max_length=50),
        ),
    ]
