# Generated by Django 3.2.9 on 2021-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_auto_20211116_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('003', 'New York'), ('005', 'Sidney'), ('35', 'Izmir'), ('61', 'Trabzon'), ('001', 'Berlin'), ('002', 'London'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('06', 'Ankara'), ('07', 'Antalya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('003', 'New York'), ('005', 'Sidney'), ('35', 'Izmir'), ('61', 'Trabzon'), ('001', 'Berlin'), ('002', 'London'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('06', 'Ankara'), ('07', 'Antalya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('901', 'Onur Air'), ('905', 'Atlasglobal'), ('904', 'Pegasus'), ('903', 'Turkish Airlines'), ('902', 'Anadolu Jet')], max_length=50),
        ),
    ]
