# Generated by Django 3.2.9 on 2021-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_auto_20211116_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('35', 'Izmir'), ('001', 'Berlin'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('002', 'London'), ('07', 'Antalya'), ('06', 'Ankara'), ('003', 'New York'), ('61', 'Trabzon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(choices=[('005', 'Sidney'), ('35', 'Izmir'), ('001', 'Berlin'), ('004', 'Tokyo'), ('34', 'Istanbul'), ('002', 'London'), ('07', 'Antalya'), ('06', 'Ankara'), ('003', 'New York'), ('61', 'Trabzon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingairlines',
            name='name',
            field=models.CharField(choices=[('903', 'Turkish Airlines'), ('905', 'Atlasglobal'), ('901', 'Onur Air'), ('904', 'Pegasus'), ('902', 'Anadolu Jet')], max_length=50),
        ),
    ]
